import { IBriefing } from "../types";

export const BriefingInitialState: IBriefing = {
    customerName: "",
    brandColor: "",
    customerLink: "http://localhost:3000",
    branchActivity: "",
    brandMission: "",
    preventColor: "",
    summaryServices: "",
    summaryStory: "",
    differentials: "",
    marketingMaterial: "no",
    marketTime: "",
    visualIdentityManual: "",
    personalities:"",
    aboutPublicTarget: "",
    publicRelationshipWithBrand:"",
    whyPublicNeedWebsite:"",
    expectedAppearance: "",
    siteObjective: "",
    siteType: "",
    siteSections: "",
    sitesReference: "",
}