export enum PersonalitiesEnum {
    formal = "Formal",
    informal = "Informal",
    funny = "Divertida",
    serious = "Séria",
    friendly = "Amigável",
    modern = "Moderna",
    old = "Antiga",
    safe = "Segura",
    robust = "Robusta",
    delicate = "Forte",
    tech = "Delicada",
    human = "Humana",
    exclusive = "Exclusiva",
    masculine = "Masculina",
    feminine = "Feminina",
    strong = "Forte",
}