import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Providers from "./provider"
import ImportBsJS from "./importBsJS"

const poppins = Poppins({ subsets: ['latin'], weight: '300' })

export const metadata: Metadata = {
  title: 'Proposta Express',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ImportBsJS />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
